package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func writeTempEnv(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), ".env")
	if err := os.WriteFile(path, []byte(body), 0644); err != nil {
		t.Fatalf("write env: %v", err)
	}
	return path
}

func TestLoadConfigProfessionalDefaults(t *testing.T) {
	cfg, err := loadConfig(writeTempEnv(t, ""))
	if err != nil {
		t.Fatalf("loadConfig returned error: %v", err)
	}

	if cfg.RunID == "" {
		t.Fatalf("RunID should be generated by default")
	}
	if !strings.HasPrefix(cfg.KeyPrefix, "s3bench/"+cfg.RunID+"/") {
		t.Fatalf("KeyPrefix = %q, want it scoped by RunID %q", cfg.KeyPrefix, cfg.RunID)
	}
	if len(cfg.ReadOps) != 1 || cfg.ReadOps[0] != opGET {
		t.Fatalf("ReadOps = %#v, want only GET by default", cfg.ReadOps)
	}
	if cfg.RangeSize != 0 {
		t.Fatalf("RangeSize = %d, want 0 by default", cfg.RangeSize)
	}
	if cfg.Retry != 0 {
		t.Fatalf("Retry = %d, want 0 by default", cfg.Retry)
	}
}

func TestLoadConfigParsesAdvancedOptions(t *testing.T) {
	envPath := writeTempEnv(t, strings.Join([]string{
		"RUN_ID=manual-run",
		"KEY_PREFIX=bench/",
		"READ_OPS=get,head,range,list",
		"RANGE_SIZE=128KB",
		"WARMUP_DURATION=3s",
		"CLEAN_AFTER=true",
		"RESULT_FILE=/tmp/s3bench-result.json",
		"RETRY=2",
		"OBJECT_SIZE_PATTERN=4KB:70%,1MB:30%",
	}, "\n"))

	cfg, err := loadConfig(envPath)
	if err != nil {
		t.Fatalf("loadConfig returned error: %v", err)
	}

	if cfg.RunID != "manual-run" {
		t.Fatalf("RunID = %q, want manual-run", cfg.RunID)
	}
	if cfg.KeyPrefix != "bench/manual-run/" {
		t.Fatalf("KeyPrefix = %q, want bench/manual-run/", cfg.KeyPrefix)
	}
	wantOps := []readOp{opGET, opHEAD, opRANGE, opLIST}
	if len(cfg.ReadOps) != len(wantOps) {
		t.Fatalf("ReadOps len = %d, want %d", len(cfg.ReadOps), len(wantOps))
	}
	for i := range wantOps {
		if cfg.ReadOps[i] != wantOps[i] {
			t.Fatalf("ReadOps[%d] = %s, want %s", i, cfg.ReadOps[i], wantOps[i])
		}
	}
	if cfg.RangeSize != 128*1024 {
		t.Fatalf("RangeSize = %d, want 128KiB", cfg.RangeSize)
	}
	if cfg.WarmupDuration != 3*time.Second {
		t.Fatalf("WarmupDuration = %s, want 3s", cfg.WarmupDuration)
	}
	if !cfg.CleanAfter {
		t.Fatalf("CleanAfter = false, want true")
	}
	if cfg.ResultFile != "/tmp/s3bench-result.json" {
		t.Fatalf("ResultFile = %q", cfg.ResultFile)
	}
	if cfg.Retry != 2 {
		t.Fatalf("Retry = %d, want 2", cfg.Retry)
	}
	if len(cfg.ObjectSizes) != 2 {
		t.Fatalf("ObjectSizes = %#v, want two entries", cfg.ObjectSizes)
	}
	if cfg.ObjectSizes[0].Size != 4*1024 || cfg.ObjectSizes[0].Weight != 70 {
		t.Fatalf("first object size entry = %#v", cfg.ObjectSizes[0])
	}
	if cfg.ObjectSizes[1].Size != 1*1024*1024 || cfg.ObjectSizes[1].Weight != 30 {
		t.Fatalf("second object size entry = %#v", cfg.ObjectSizes[1])
	}
}

func TestClassifyError(t *testing.T) {
	cases := []struct {
		name string
		err  error
		want string
	}{
		{name: "nil", err: nil, want: "ok"},
		{name: "status", err: &s3Error{Op: "GET", StatusCode: 404, Status: "404 Not Found"}, want: "GET status=404"},
		{name: "timeout", err: os.ErrDeadlineExceeded, want: "timeout"},
		{name: "connection reset", err: errString("read: connection reset by peer"), want: "connection_reset"},
		{name: "other", err: errString("boom"), want: "other"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := classifyError(tc.err); got != tc.want {
				t.Fatalf("classifyError(%v) = %q, want %q", tc.err, got, tc.want)
			}
		})
	}
}

type errString string

func (e errString) Error() string { return string(e) }
